#!/bin/bash

numberRegExp='^[0-9]+$'

if ! [[ ${1} =~ ${numberRegExp} ]] ; then
    echo "Please use a number as an argument.   This number will be the number of Geode Systems configured in a mesh topolgy."
    exit 1
fi
if ! (( ${1} > 1 )) ; then
  echo "Please use more then 1 system in the example."
  exit 1
fi
# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >&-
APP_HOME="`pwd -P`"
cd "$SAVED" >&-

numberOfSystems=${1}

function configureSystem(){

  local currentSystemId=${1}
  local j=0
  local senders=
  for (( j=1; j<=${numberOfSystems}; j++ )) ; do
      if (( ${currentSystemId} != $j )) ; then
        if ! [ -z "$senders" ] ; then
          senders="${senders},sender${j}"
        else
          senders="sender${j}"
        fi
        gfsh -e "connect --locator=localhost[1033${currentSystemId}]" -e "create gateway-sender --id='sender$j' --parallel=true --remote-distributed-system-id='$j'" | egrep "^\(2\)" | (paste /dev/null -)
      fi
  done
  gfsh -e "connect --locator=localhost[1033${currentSystemId}]" -e "create gateway-receiver" | egrep "^\(2\)" | (paste /dev/null -)

  # I wanted to randomly configure the region and WAN gateway to show it can be
  # done after region creation or at the time the region gets created.
  configureDifferently=$(( $RANDOM % 2 ))
  if (( $configureDifferently == 0 )) ; then
    # Configure the region and gateway all at once
    gfsh -e "connect --locator=localhost[1033${currentSystemId}]" -e "create region --name=test --type=PARTITION --gateway-sender-id=${senders}" | egrep "^\(2\)" | (paste /dev/null -)
  else
    # Add the gateway to an existting region
    gfsh -e "connect --locator=localhost[1033${currentSystemId}]" -e "create region --name=test --type=PARTITION" | egrep "^\(2\)" | (paste /dev/null -)
    gfsh -e "connect --locator=localhost[1033${currentSystemId}]" -e "alter region --name=test --gateway-sender-id=${senders}" | egrep "^\(2\)" | (paste /dev/null -)
  fi
}

for (( i=1; i<=${numberOfSystems}; i++ )) ; do
  configureSystem ${i} &
done

wait
